### ISSUE TITLE
Compatibility with node.js

### ISSUE THREAD

**Issue by tylerlong** [knsv/mermaid#257]
I first installed mermaid via `npm install mermaid`
Then I created `index.temp.js` with only one line: `require('mermaid'); `

It doesn't work for me:
```
$ node index.temp.js 
/some-path/node_modules/mermaid/src/mermaid.js:19
import * as Logger from './logger';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/tylerlong/src/js/markdown-core/index.temp.js:1:63)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

**Comment by knsv** [comment]
I am using es2015 features. The pre-compiled libraries have been transformed to ecmascript5 via babel.

If you use require directly you need to apply babel yourself. 

This has caused me some headache and I am thinking of rolling back to not use es2015 yet. Still deciding though.

**Comment by knsv** [comment]
Closing issue as it's resolution is included in release 0.5.6. Let me know if you do not agree.

**Comment by tylerlong** [comment]
:+1:  I will have a try. If I don't repond, then it meas I find no problem.

Thank you for your work!

**Comment by tylerlong** [comment]
It works with node.js now.

But it still depends on browser, you cannot do purely in node.js.

I found this todo in code: https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js#L486

I will create a separate todo for this.
