### ISSUE TITLE
npm run watch doesn’t work due missing dependencies

### ISSUE THREAD

**Issue by jirutka** [knsv/mermaid#266]
I’ve tried it with both npm 2.x and 3.x with the same result.

```
npm install
...
npm run watch

> mermaid@0.5.6 watch /Users/jimmy/Temp/mermaid
> source  ./scripts/watch.sh

./scripts/watch.sh: line 3: watchify: command not found
./scripts/watch.sh: line 4: live-server: command not found
module.js:339
    throw err;
    ^

Error: Cannot find module 'brace-expansion'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/jimmy/Temp/mermaid/node_modules/eslint/node_modules/minimatch/minimatch.js:10:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/var/lib/nodenv/versions/4.2.3/bin/node" "/usr/local/var/lib/nodenv/versions/4.2.3/bin/npm" "run" "watch"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! mermaid@0.5.6 watch: `source  ./scripts/watch.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mermaid@0.5.6 watch script 'source  ./scripts/watch.sh'.
npm ERR! This is most likely a problem with the mermaid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     source  ./scripts/watch.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls mermaid
npm ERR! There is likely additional logging output above.
```

**Comment by knsv** [comment]
Thanks. Will add them!

**Comment by tylerlong** [comment]
No longer relevant.
