### ISSUE TITLE
live editor latin error after update

### ISSUE THREAD

**Issue by willin** [knsv/mermaid#560]
```
graph TB
  s(start) --> step1[开始]
```

```
Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at e.value (https://mermaidjs.github.io/mermaid-live-editor/index.bundle.js:52:261029)
    at t.handleTextareaChange (https://mermaidjs.github.io/mermaid-live-editor/index.bundle.js:25:519928)
    at Object.executeOnChange (https://mermaidjs.github.io/mermaid-live-editor/index.bundle.js:25:3810)
    at m.i (https://mermaidjs.github.io/mermaid-live-editor/index.bundle.js:25:568987)
    at Object.r (https://mermaidjs.github.io/mermaid-live-editor/index.bundle.js:11:103236)
    at o (https://mermaidjs.github.io/mermaid-live-editor/index.bundle.js:11:101586)
    at Object.u [as executeDispatchesInOrder] (https://mermaidjs.github.io/mermaid-live-editor/index.bundle.js:11:101801)
    at h (https://mermaidjs.github.io/mermaid-live-editor/index.bundle.js:11:17209)
    at m (https://mermaidjs.github.io/mermaid-live-editor/index.bundle.js:11:17335)
    at Array.forEach (<anonymous>)
```

**Comment by tylerlong** [comment]
Got it, I will fix it.

**Comment by tylerlong** [comment]
Fixed: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEIKICBzKHN0YXJ0KSAtLT4gc3RlcDFb5byA5aeLXQ==

![image](https://user-images.githubusercontent.com/733544/29392744-49ed5a34-8332-11e7-916c-0e4c47bb2570.png)
