### ISSUE TITLE
Cannot read property 'initialize' of undefined, inoperable in an AMD/requirejs environment in Jupyter Notebook

### ISSUE THREAD

**Issue by Honghe** [knsv/mermaid#662]
Environment:
* Jupyter version: 4.4.0

```
%%javascript
require(["https://unpkg.com/mermaid@8.0.0-rc.8/dist/mermaid.js"], function(mermaid){
    console.log(mermaid)
    mermaid.initialize({startOnLoad:true})
})
```
console log:
```
undefined
require.js?v=6da8be361b9ee26c5e721e76c6d4afce:900 TypeError: Cannot read property 'initialize' of undefined
    at eval (eval at append_javascript (outputarea.js:757), <anonymous>:3:13)
    at Object.execCb (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1690)
    at Module.check (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:865)
    at Module.enable (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1177)
    at Module.init (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:783)
    at require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1453
check @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:900
enable @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1177
init @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:783
(anonymous) @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1453
setTimeout (async)
req.nextTick @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1809
localRequire @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1442
requirejs @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1791
(anonymous) @ VM18579:1
append_javascript @ outputarea.js:757
OutputArea.append_mime_type @ outputarea.js:691
OutputArea.append_display_data @ outputarea.js:654
OutputArea.append_output @ outputarea.js:346
OutputArea.handle_output @ outputarea.js:257
output @ codecell.js:376
Kernel._handle_output_message @ kernel.js:1196
f @ jquery.min.js:2
Kernel._handle_iopub_message @ kernel.js:1223
Kernel._finish_ws_message @ kernel.js:1015
(anonymous) @ kernel.js:1006
Promise.then (async)
Kernel._handle_ws_message @ kernel.js:1006
f @ jquery.min.js:2
[Violation] Forced reflow while executing JavaScript took 37ms
```

**Comment by RobertHue** [comment]
Hello! I'm experiencing the same issue:

(etf) rhuemmer@PCAED685:~/etf$ ./node_modules/.bin/mmdc -i ./doc/sphinx/source/hardware/linux/tcp_client.mmd -o test.png -p ./doc/sphinx/source/puppeteer-config.json 
/home/rhuemmer/etf/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read property 'initialize' of undefined
    at __puppeteer_evaluation_script__:3:20
    at ExecutionContext._evaluateInternal (/home/rhuemmer/etf/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async ExecutionContext.evaluate (/home/rhuemmer/etf/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
    at async ElementHandle.evaluate (/home/rhuemmer/etf/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:102:16)
    at async ElementHandle.$eval (/home/rhuemmer/etf/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:650:24)
(etf) rhuemmer@PCAED685:~/etf$


Puppeteer und mermaid.cli are the latest version:

(etf) rhuemmer@PCAED685:~/etf$ npm list --depth=1
etf@ /home/rhuemmer/etf
├─┬ @mermaid-js/mermaid-cli@8.8.2-beta.8
│ ├── chalk@4.1.0
│ ├── commander@6.2.0
│ └── puppeteer@5.4.1
├─┬ bufferutil@4.0.2
│ └── node-gyp-build@4.2.3
├─┬ chromium@3.0.2
│ ├── cachedir@2.3.0
│ ├── debug@4.2.0
│ ├── extract-zip@1.7.0
│ ├── got@11.8.0
│ ├── progress@2.0.3
│ ├── rimraf@2.7.1
│ ├── tmp@0.0.33
│ └── tunnel@0.0.6
└─┬ utf-8-validate@5.0.3
  └── node-gyp-build@4.2.3 deduped

What could be the problem?
